### ISSUE TITLE
Install on Windows

### ISSUE THREAD

**Issue by nagim** [cthos/atom-gitbook#48]
Sorry to log this as an issue, but found no other interface.
How should this be installed on Windows? I tried to copy the code to the Packages folder, but it gave me an error on startup.

Thanks!

**Comment by cthos** [comment]
Hi @nagim - It should be the same procedure as Mac / Linux, but I've not explicitly tried it on Windows. I can give it a shot today or tomorrow and get back to you.

What's the error?

It's possible you'll need to do `apm rebuild` instead of `npm install` in the folder as well.

**Comment by cthos** [comment]
I've successfully installed this on Windows, with `apm install` in the given directory. I'll update the readme since it should probably be apm instead of npm anyhow. Lemme know if this doesn't work!

**Comment by nagim** [comment]
Thanks for the support, I tried and I can verify that it works fine.
