### ISSUE TITLE
Use gitbook-parsers or gitbook-markdown

### ISSUE THREAD

**Issue by SamyPesse** [cthos/atom-gitbook#56]
Awesome plugin :+1: 

Why not use https://github.com/GitbookIO/gitbook-parsers or https://github.com/GitbookIO/gitbook-markdown for parsing `SUMMARY.md`?

**Comment by cthos** [comment]
Thanks! :tada:

For the parser, I only just discovered you'd made that package a few weeks ago, but I didn't want to implement it until #29 was finished so I could be sure I didn't break anything.

It's definitely on the todo list, and this issue will serve as the action item.
