### ISSUE TITLE
package causes atom to freeze

### ISSUE THREAD

**Issue by nagim** [cthos/atom-gitbook#57]
Hi,

Whenever I install and try to load/toggle atom-gitbook, the atom window freezes, I have to start a new window and shut down the other one.
Only uninstall helps.
Any ideas what could be the issue? I tried `apm rebuild`, but no avail.
Here is my [package list](https://github.com/cthos/atom-gitbook/files/126496/package-list.txt), if it helps.

Thanks,
Imre

**Comment by cthos** [comment]
Hmm, could be something's getting stuck in a loop. What do your `book.json` and `summary.md` files look like?

If you open the console (cmd + option + i), before activating the package, does anything appear in there?

**Comment by nagim** [comment]
`SUMMARY.md`:

``` markdown
# Summary

* [Welcome](README.md)
* [Ascii](ascii.adoc)
   * [rST](sdk.rst)
* [New Section]
   * [Chapter 1](chapter1.md)
```

`book.json`:

``` json
{
    "plugins": [
        "comment",
        "include",
        "-sharing",
        "anchor-navigation",
        "heading-anchors",
        "ungrey",
        "toggle-chapters",
        "book-summary-scroll-position-saver",
        "splitter",
        "versions",
        "richquotes",
        "copy-code-button",
        "codesnippet",
        "sections"
    ],
    "pluginsConfig": {
        "versions": {
            "type": "branches"
        },
        "richquotes": {
            "danger": {
                "alert": "danger",
                "picto": "fa-exclamation-triangle"
            }
        }
    },
    "variables": {
        "process": "install"
    }
}
```

I cannot check the console now, as I'm on my home computer now, will check tomorrow.

Thanks!

**Comment by nagim** [comment]
I checked with the console running.
I enabled it (my gitbook folder and some files was open in atom), then quit atom, installed the package.
On startup, it froze, nothing loaded, only the menu bar, had to start a new window and force close this.

In the new window, opened the gitbook project, console, then selected atom-gitbook from packages, clicked **Toggle**.
It froze again, console did not show new stuff, only these (showed them after startup):

```
C:\Users\username\AppData\Local\atom\app-1.5.2\resources\app.asar\src\text-editor-component.js:957 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
C:\Users\username\AppData\Local\atom\app-1.5.2\resources\app.asar\src\text-editor-component.js:957 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
```

Thanks,
Imre

**Comment by nagim** [comment]
One adddition: commands both from right click menu and command palette seems to be working (like Add as a chapter, Insert as GitBook include, Organize chapters).
Only when I try to toggle the ToC, it freezes.

**Comment by cthos** [comment]
Yeah, that's definitely weird. Let me try and duplicate the issue. It might take me a bit before I can get to it though.

**Comment by nagim** [comment]
Yes, no problem! Thank you so much!

**Comment by cthos** [comment]
@nagim So I can reproduce this with your `summary.md` file. 90% odds that it's a bug and it's getting caught up when it tries to parse the summary file.

**Comment by cthos** [comment]
Okay, so definitely a bug, I've created #58 to track it.

In the meantime, when you've got tabs before the sub items in your summary.md file, you'll need to use an even number of spaces (the default it looks for is 2 spaces).

So instead of:

``` md
* [Ascii](ascii.adoc)
   * [rST](sdk.rst)
```

You'd want:

``` md
* [Ascii](ascii.adoc)
  * [rST](sdk.rst)
```

Sorry about that, I thought I had better error handling around that bit.

**Comment by nagim** [comment]
Wow, thanks a lot, you were really quick! Awesome, I will keep that in mind!

**Comment by cthos** [comment]
:+1:

**Comment by nagim** [comment]
:beers:
